services:
  - type: web
    name: e-waste-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

      - key: FLASK_URL
        fromService:
          type: web
          name: e-waste-ml
          envVarKey: RENDER_EXTERNAL_URL
      - key: CV_URL
        fromService:
          type: web
          name: e-waste-cv
          envVarKey: RENDER_EXTERNAL_URL
      - key: LOG_LEVEL
        value: info
      - key: ML_REQUEST_TIMEOUT_MS
        value: 60000

  - type: web
    name: e-waste-ml
    runtime: python
    region: singapore
    plan: free
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"

  - type: web
    name: e-waste-cv
    runtime: python
    region: singapore
    plan: free
    rootDir: cv-service
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"



